{{- if .Values.externalGalera.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalGalera.passwordSecretName }} # Name of the secret
  labels:
    {{- include "proxysql-k8s-discovery.labels" . | nindent 4 }} # Common labels
    app.kubernetes.io/component: proxysql-updater # Component label
type: Opaque
data:
  password: {{ .Values.externalGalera.monitorPassword | b64enc | quote }} # Base64 encoded password
{{- end }}
