apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-k8s-discovery.proxysqlClusterSecretName" . }}
  labels:
    {{- include "proxysql-k8s-discovery.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
type: Opaque
data:
  password: {{ .Values.proxysql.cluster_password | b64enc | quote }}