apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql-k8s-discovery.proxysqlHeadlessServiceName" . }} # Name of the headless service
  labels:
    {{- include "proxysql-k8s-discovery.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
spec:
  clusterIP: None # This makes it a headless service
  selector:
    {{- include "proxysql-k8s-discovery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
  ports:
    - protocol: TCP
      port: 6032 # Admin port
      targetPort: 6032
      name: admin
    - protocol: TCP
      port: 6033 # Client port
      targetPort: 6033
      name: client
