apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-k8s-discovery.proxysqlAdminSecretName" . }}
  labels:
    {{- include "proxysql-k8s-discovery.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
type: Opaque
data:
  password: {{ .Values.proxysql.adminPassword | b64enc | quote }}