apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql-k8s-discovery.proxysqlServiceName" . }}
  labels:
    {{- include "proxysql-k8s-discovery.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
spec:
  type: ClusterIP
  selector:
    {{- include "proxysql-k8s-discovery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
  ports:
    - protocol: TCP
      port: 6032
      targetPort: 6032
      name: admin
    - protocol: TCP
      port: 6033
      targetPort: 6033
      name: client
